name: 'Trainstats Realtime DigitalOcean Push'

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ${{secrets.DOCKER_REGISTRY}}
  DOCKER_REPOSITORY: ${{ secrets.DIGITAL_OCEAN_REGISTRY_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: 'Build and Push to DigitalOcean'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Go application
        run: |
          cd cmd/api
          go build -v -o ../../app .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and push image to DigitalOcean Container Registry
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG

      - name: Print image details
        run: echo "Image pushed to $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"