name: 'Trainstats Realtime ECR Push'

on:
  push:
    branches:
      - main

env:
  AWS_REGION: 'us-east-1'
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_URL }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: 'Build and Push to ECR'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build Go application
        run: go build -v -o app .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Print image details
        run: echo "Image pushed to ${{ steps.build-and-push.outputs.image }}"